report 50004 "Report With Labels"
{
    dataset
    {
    }

    var
        TitleLbl: Label 'Invoice Report';
        SubtitleLbl: Label 'Generated by AL Runner';

    procedure GetTitle(): Text
    begin
        exit(TitleLbl);
    end;

    procedure GetSubtitle(): Text
    begin
        exit(SubtitleLbl);
    end;
}

codeunit 50356 "Report Label Helper"
{
    procedure GetReportTitle(): Text
    var
        r: Report "Report With Labels";
    begin
        exit(r.GetTitle());
    end;

    procedure GetReportSubtitle(): Text
    var
        r: Report "Report With Labels";
    begin
        exit(r.GetSubtitle());
    end;
}
